[package]
name = "ogmarkup"
version = "0.1.0"
authors = ["Thomas Letan <contact@thomasletan.fr>"]

[features]
default = []
html = ["maud"]

[dependencies]
nom = "5.0.0"

[dependencies.maud]
version = "0.20"
optional = true
